-- Full User Seeds
INSERT INTO users (name, email, password, current_field, desired_field, skills, experience, location, social_media_link, profile_image_url, bio)
VALUES
    ('Alice Johnson', 'alice@example.com', 'password123', 'Marketing', 'Product Management', 'Communication, Teamwork', '5 years', 'New York, NY', 'https://linkedin.com/in/alicejohnson', 'https://randomuser.me/api/portraits/women/44.jpg', 'Passionate about transitioning to product management.'),
    ('Bob Smith', 'bob@example.com', 'securepassword', 'Software Engineering', 'Data Science', 'Python, SQL, Machine Learning', '3 years', 'San Francisco, CA', 'https://linkedin.com/in/bsmith', 'https://randomuser.me/api/portraits/men/21.jpg', 'Looking to break into data science after several years of software engineering.'),
    ('Catherine Lee', 'catherine@example.com', 'mypassword', 'Graphic Design', 'UX Design', 'Adobe Photoshop, Illustrator, Figma', '4 years', 'Toronto, ON', 'https://linkedin.com/in/catherinelee', 'https://randomuser.me/api/portraits/women/45.jpg', 'Creative professional interested in UX and human-centered design.'),
    ('David Kim', 'david@example.com', 'password456', 'Finance', 'Business Analysis', 'Financial Modeling, Data Analysis', '7 years', 'Chicago, IL', 'https://linkedin.com/in/davidkim', 'https://randomuser.me/api/portraits/men/28.jpg', 'Experienced finance professional interested in business analysis roles.'),
    ('Ella Rodriguez', 'ella@example.com', 'password789', 'Teaching', 'EdTech', 'Curriculum Development, Instruction', '6 years', 'Miami, FL', 'https://linkedin.com/in/ellarodriguez', 'https://randomuser.me/api/portraits/women/47.jpg', 'Educator passionate about using technology to improve learning experiences.'),
    ('John Doe', 'john.doe1@example.com', 'password123', 'Frontend Developer', 'Fullstack Development', 'JavaScript, HTML, CSS, React', '3 years', 'Los Angeles, CA', 'https://linkedin.com/in/johndoe1', 'https://randomuser.me/api/portraits/men/1.jpg', 'Frontend developer passionate about creating visually appealing and user-friendly websites.'),
    ('Jane Doe', 'jane.doe2@example.com', 'password123', 'Frontend Developer', 'UX Design', 'JavaScript, HTML, CSS, React', '4 years', 'Seattle, WA', 'https://linkedin.com/in/janedoe2', 'https://randomuser.me/api/portraits/women/2.jpg', 'Frontend developer focused on bridging the gap between design and development.'),
    ('Mike Johnson', 'mike.johnson3@example.com', 'password123', 'Frontend Developer', 'Backend Development', 'JavaScript, HTML, CSS, React', '2 years', 'Austin, TX', 'https://linkedin.com/in/mikejohnson3', 'https://randomuser.me/api/portraits/men/3.jpg', 'Specializing in React and frontend tools to create efficient and robust applications.'),
    ('Emily Smith', 'emily.smith4@example.com', 'password123', 'Frontend Developer', 'Product Management', 'JavaScript, HTML, CSS, React', '5 years', 'Boston, MA', 'https://linkedin.com/in/emilysmith4', 'https://randomuser.me/api/portraits/women/4.jpg', 'Creative developer with a passion for front-end technologies and clean UI.'),
    ('Chris Adams', 'chris.adams5@example.com', 'password123', 'Frontend Developer', 'Data Science', 'JavaScript, HTML, CSS, React', '3 years', 'Denver, CO', 'https://linkedin.com/in/chrisadams5', 'https://randomuser.me/api/portraits/men/5.jpg', 'Driven by an interest in building seamless web interfaces with React.'),
    ('Sophie Williams', 'sophie.williams6@example.com', 'password123', 'Frontend Developer', 'Fullstack Development', 'JavaScript, HTML, CSS, React', '3 years', 'Chicago, IL', 'https://linkedin.com/in/sophiewilliams6', 'https://randomuser.me/api/portraits/women/6.jpg', 'Dedicated to building responsive, high-quality frontend experiences.'),
    ('Daniel Brown', 'daniel.brown7@example.com', 'password123', 'Frontend Developer', 'Cloud Computing', 'JavaScript, HTML, CSS, React', '4 years', 'Phoenix, AZ', 'https://linkedin.com/in/danielbrown7', 'https://randomuser.me/api/portraits/men/7.jpg', 'Frontend developer with a focus on performant and scalable UI systems.'),
    ('Laura White', 'laura.white8@example.com', 'password123', 'Frontend Developer', 'Project Management', 'JavaScript, HTML, CSS, React', '2 years', 'Dallas, TX', 'https://linkedin.com/in/laurawhite8', 'https://randomuser.me/api/portraits/women/8.jpg', 'Passionate about using technology to solve creative challenges.'),
    ('Tom Green', 'tom.green9@example.com', 'password123', 'Frontend Developer', 'Backend Development', 'JavaScript, HTML, CSS, React', '3 years', 'Philadelphia, PA', 'https://linkedin.com/in/tomgreen9', 'https://randomuser.me/api/portraits/men/9.jpg', 'Love building smooth and interactive user experiences.'),
    ('Anna King', 'anna.king10@example.com', 'password123', 'Frontend Developer', 'UX Research', 'JavaScript, HTML, CSS, React', '3 years', 'San Francisco, CA', 'https://linkedin.com/in/annaking10', 'https://randomuser.me/api/portraits/women/10.jpg', 'Frontend enthusiast with an interest in user research and design.'),
    ('Sam Taylor', 'sam.taylor11@example.com', 'password123', 'Frontend Developer', 'Fullstack Development', 'JavaScript, HTML, CSS, React', '3 years', 'San Diego, CA', 'https://linkedin.com/in/samtaylor11', 'https://randomuser.me/api/portraits/men/11.jpg', 'Focused on building and maintaining scalable user-facing applications.'),
    ('Olivia Scott', 'olivia.scott12@example.com', 'password123', 'Frontend Developer', 'Product Design', 'JavaScript, HTML, CSS, React', '4 years', 'Portland, OR', 'https://linkedin.com/in/oliviascott12', 'https://randomuser.me/api/portraits/women/12.jpg', 'Frontend specialist interested in creating great user experiences.'),
    ('Henry Moore', 'henry.moore13@example.com', 'password123', 'Frontend Developer', 'Mobile Development', 'JavaScript, HTML, CSS, React', '3 years', 'Las Vegas, NV', 'https://linkedin.com/in/henrymoore13', 'https://randomuser.me/api/portraits/men/13.jpg', 'Excited about building responsive applications for all screen sizes.'),
    ('Ella Brooks', 'ella.brooks14@example.com', 'password123', 'Frontend Developer', 'DevOps', 'JavaScript, HTML, CSS, React', '5 years', 'Houston, TX', 'https://linkedin.com/in/ellabrooks14', 'https://randomuser.me/api/portraits/women/14.jpg', 'Passionate about frontend tools and their role in development.'),
    ('James Hall', 'james.hall15@example.com', 'password123', 'Frontend Developer', 'AI Development', 'JavaScript, HTML, CSS, React', '4 years', 'Atlanta, GA', 'https://linkedin.com/in/jameshall15', 'https://randomuser.me/api/portraits/men/15.jpg', 'Frontend developer looking to move into the AI field.');
